<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta charset="utf-8" />
    <meta name="description" content="Credit Conveyer - займы">
    <meta name="keywords" content="Credit, Conveyer, займы, деньги">
    <meta property="og:title" content="Credit Conveyer"/>
    <meta property="og:description" content="Credit Conveyer - Выдача денег"/>
    <meta property="og:site_name" content="Credit Conveyer" />
    <meta property="og:type" content="website">
    <meta property="og:url" content="<?=getHttpHost()?><?=$this->url()?>">
    <meta property="og:image" itemprop="ïmage" content="http://uz.cheesenology.kz/design/img/logo.png" />
    <meta property="og:image:secure_url" itemprop="ïmage" content="https://uz.cheesenology.kz/design/img/logo.png" />
    <meta property="og:image:type" content="image/png" />
    <meta property="og:image:width" content="88" />
    <meta property="og:image:height" content="40" />
    <meta property="og:image:alt" content="Credit Conveyer" />
    <title>Mebel CRM</title>

<!--    <link rel="icon" href="/version_2.0/ace_admin/assets/images/favicon/favicon2.ico?v=2.0" type="image/x-icon">-->
<!--    <link rel="shortcut icon" href="/version_2.0/ace_admin/assets/images/favicon/favicon2.ico?v=2.0" type="image/x-icon">-->

    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/jquery-ui-1.11.2/jquery-ui.css">
    <!-- bootstrap & fontawesome -->
    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/font-awesome/4.5.0/css/font-awesome.min.css" />

    <!-- page specific plugin styles -->
    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/css/colorbox.min.css" />

    <!-- text fonts -->
    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/css/fonts.googleapis.com.css?v=2" />

    <!-- ace styles -->
    <!--    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/css/jquery-ui.min.css" />-->
    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/css/ace.min.css" class="ace-main-stylesheet" id="main-ace-style" />

    <!--[if lte IE 9]>
    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/css/ace-part2.min.css" class="ace-main-stylesheet" />
    <![endif]-->
    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/css/ace-skins.min.css" />
    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/css/ace-rtl.min.css" />

    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/css/chosen.min.css" />

    <!--[if lte IE 9]>
    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/css/ace-ie.min.css" />
    <![endif]-->

    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/slick/slick.css">
    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/slick/slick-theme.css">

    <!-- bebek styles -->
    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/css/style.css?v=13" />


    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/treetable/css/jquery.treetable.css" />
    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/treetable/css/jquery.treetable.theme.default.css" />
    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/treetable/css/screen.css" />
    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/css/simplelightbox.min.css" />
    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/passfield/css/passfield.min.css" />
    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/remodal/remodal.css" />
    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/remodal/remodal-default-theme.css" />
    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/tooltipster/css/tooltipster.bundle.min.css" />

<!--    <link rel="stylesheet" href="/version_2.0/tablesorter/css/theme.default.css">-->
    <!-- inline styles related to this page -->

    <!-- ace settings handler -->
    <script src="/version_2.0/ace_admin/assets/js/ace-extra.min.js"></script>

    <!-- HTML5shiv and Respond.js for IE8 to support HTML5 elements and media queries -->

    <!--[if lte IE 8]>
    <script src="/version_2.0/ace_admin/assets/js/html5shiv.min.js"></script>
    <script src="/version_2.0/ace_admin/assets/js/respond.min.js"></script>
    <![endif]-->

    <!-------------------------------------------javascripts----------------------------------------------------->
    <!-- basic scripts -->

    <!--[if !IE]> -->
    <script src="/version_2.0/ace_admin/assets/js/jquery-2.1.4.min.js"></script>

    <!-- <![endif]-->
    
    <!--[if IE]>
    <script src="/version_2.0/ace_admin/assets/js/jquery-1.11.3.min.js"></script>
    <![endif]-->
    <script type="text/javascript">
        if('ontouchstart' in document.documentElement) document.write("<script src='/version_2.0/ace_admin/assets/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
    </script>

<!--    <script src="/version_2.0/ace_admin/assets/js/jquery-ui.min.js"></script>-->
    <script src="/version_2.0/ace_admin/assets/jquery-ui-1.11.2/jquery-ui.js"></script>
    <script src="/version_2.0/ace_admin/assets/js/bootstrap.min.js"></script>

    <!-- page specific plugin scripts -->
    <script src="/version_2.0/ace_admin/assets/js/jquery.colorbox.min.js"></script>

    <!-- ace scripts -->
    <script src="/version_2.0/ace_admin/assets/js/ace-elements.min.js"></script>
    <script src="/version_2.0/ace_admin/assets/js/ace.min.js"></script>
    <script src="/version_2.0/ace_admin/assets/js/chosen.jquery.min.js"></script>
    <script src="/version_2.0/ace_admin/assets/js/jquery.maskedinput.min.js"></script>
    <script src="/version_2.0/ace_admin/assets/treetable/jquery.treetable.js"></script>
    <script src="/version_2.0/ace_admin/assets/js/autosize.min.js"></script>
    <script src="/version_2.0/ace_admin/assets/js/jquery.inputlimiter.min.js"></script>
    <script src="/version_2.0/ace_admin/assets/js/simple-lightbox.min.js"></script>
    <script src="/version_2.0/ace_admin/assets/js/bootstrap-confirmation.min.js"></script>
    <script src="/version_2.0/ace_admin/assets/passfield/js/passfield.min.js"></script>
    <script src="/version_2.0/ace_admin/assets/slick/slick.min.js"></script>
    <script src="/version_2.0/ace_admin/assets/remodal/remodal.js"></script>
    <script src="/version_2.0/ace_admin/assets/nic_edit/nicEdit.js"></script>
    <script src="/version_2.0/ace_admin/assets/tooltipster/js/tooltipster.bundle.min.js"></script>
    <script src="/version_2.0/ace_admin/assets/ckeditor/ckeditor.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@7.28.11/dist/sweetalert2.all.min.js"></script>
    <script src="/version_2.0/ace_admin/assets/js/spinbox.min.js"></script>

    <script src="/tinymce/js/tinymce/tinymce.min.js"></script>

    <!-- inline scripts related to this page -->
    <!-- load jQuery and tablesorter scripts -->
    <script type="text/javascript" src="/version_2.0/tablesorter/js/jquery.tablesorter.js"></script>

    <!-- tablesorter widgets (optional) -->
<!--    <script type="text/javascript" src="version_2.0/tablesorter/js/jquery.tablesorter.widgets.js"></script>-->
    <!-- bebek scripts -->
    <script src="/version_2.0/ace_admin/assets/js/utils.js?v=12"></script>
</head>

