<div class="page-header">
    <h1 class="pull-left">Создание новой заявки</h1>
    <div class="clearfix"></div>
</div>
<form id="form_modal_acount" method="post">
    <div class="col-sm-4">
        <div class="form-group">
            <label class="control-label" for="client_fio">ФИО клиента</label>
            <input type="text" class="form-control" name="client_fio" id="account_name">
            <div class="clearfix"></div>
        </div>

        <div class="form-group">
            <label class="control-label" for="address">Адрес</label>
            <input type="text" class="form-control" name="address" id="address" >
            <div class="clearfix"></div>
        </div>

        <div class="form-group">
            <label class="control-label" for="client_phone">Телефон</label>
            <input type="text" class="form-control phone" name="client_phone" id="client_phone" >
            <div class="clearfix"></div>
        </div>


        <div class="form-group">
            <label class="control-label" for="house_area">Площадь</label>
            <input type="text" class="form-control" name="house_area" id="house_area" >
            <div class="clearfix"></div>
        </div>

        <div class="form-group">
            <label class="control-label" for="measure_time">Время замера</label>
            <input type="text" class="date-picker" name="measure_time" id="measure_time" autocomplete="off" style="width: 100px; height: 34px;" >

            <div class="clearfix"></div>
        </div>

        <div class="form-group">
            <label for="info">Комментарий от клиента</label>
            <textarea id="client_comment" name="client_comment" class="autosize-transition form-control"></textarea>
        </div>

        <button type="button" onclick="create_request()" class="btn btn-sm btn-success">
            <i class="ace-icon fa fa-check"></i>
            Сохранить
        </button>
    </div>
</form>

<script>
    $( document ).ready(function() {
        $(".phone").mask("+7(999) 999 99 99");
    });
    function create_request(){
        var fd = new FormData($("#form_modal_acount")[0]);
        $.ajax({
            type: 'POST',
            url: "/dict/create-request/mode/upd/",
            data: fd,
            success: function(data){
                console.log(data);
                if(data.result['status'] == false){
                    alert(data.result['error']);
                    Notify.generate('Ошибка при добавлении', '', 3);
                } else{
                    Notify.generate('Успешно', '', 1);
                    window.location.href = '/dict/request-edit/request_id/' + data.result['value'];
                }
            },
            cache: false,
            contentType: false,
            processData: false
        });
    }
</script>

