<?
if (isset($this->row['error'])) {?>
    <div class="alert alert-danger">
        <?=$this->row['error']?>
    </div>
    <?
}?>
<div class="modal-body">
    <form id="client_request_doc_form">
        <input type="hidden" name="request_id" value="<?=$this->request_id?>">
        <div class="form-group">
            <label class="control-label " for="document_type_id">Тип документа</label>
            <div class="form-control no-padding">
                <select class="form-control" id="document_type_id" name="document_type_id" required>
                    <option value="0">Выберите тип файла</option>
                    <?
                    if(mycount($this->doc_type) > 0){
                        foreach ($this->doc_type as $key => $value){?>
                            <option value="<?=$value['document_type_id']?>"><?=$value['name']?></option>
                            <?
                        }
                    }?>
                </select>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="form-group">
            <label class="control-label " for="upload">Файл</label>
            <div class="form-control no-padding">
                <input type="file" name="upload" id="upload" >
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </form>
</div>
<div class="modal-footer no-margin-top">
    <button type="button" class="btn btn-sm btn-success" onclick="client_request_upd_doc()">
        <i class="ace-icon fa fa-check"></i>
        Сохранить
    </button>
    <button class="btn btn-sm btn-danger" data-dismiss="modal">
        <i class="ace-icon fa fa-times"></i>
        Закрыть
    </button>
</div>

<script>
    $(document).ready(function() {
        $(".date-picker").datepicker({
            changeMonth: true,
            changeYear: true,
            yearRange: "-100:+5"
        });
    });
</script>