<div class="page-header">
    <h1 class="pull-left">Запросы работников</h1>
    <div class="clearfix"></div>
</div>
<div class="hr hr-10 dotted hr-double"></div>
<a href="javascript:void(0)" onclick="type_edit_show()" class="btn btn-info btn-xs pull-right">Добавить</a>
<div class="clearfix"></div>
<div class="row-fluid">
    <div class="tabbable">
        <table id="main_table" class="table-local table-striped table-bordered hover-table no-margin-bottom no-border-top">
            <thead>
            <tr>
                <th>ID</th>
                <th>Запрос</th>
                <th>Кто</th>
                <th>Дата</th>
                <th>Статус</th>
            </tr>
            </thead>
            <tbody>
            <?
            if(mycount($this->row) > 0){
                foreach ($this->row as $key => $value){?>
                    <tr>
                        <td class="text-right"><?=$value['employee_needs_id']?></td>
                        <td class="text-left"><?=$value['comment']?></td>
                        <td class="text-left"><?=$value['fio']?></td>
                        <td class="text-left"><?=$value['needs_date']?></td>
                        <td class="text-left">
                        <?if(in_array(getCurPositionCode(), array('ADMIN', 'suplier'))){?>
                            <select onchange="saveStatus(<?=$value['employee_needs_id']?>, this)" class="chosen-select form-control">
                                <option value="1" <?if($value['status_id'] == 1){?>selected<?}?>>Создан</option>
                                <option value="2" <?if($value['status_id'] == 2){?>selected<?}?>>Принят</option>
                                <option value="3" <?if($value['status_id'] == 3){?>selected<?}?>>Отказано</option>
                                <option value="4" <?if($value['status_id'] == 4){?>selected<?}?>>Завершен</option>
                            </select>
                        <?}?>
                        </td>
                    </tr>
                    <?
                }
            }
            ?>
            </tbody>
        </table>
    </div>
</div>
<?=$this->partial('dict/modal-container.phtml');?>

<script>
    $(document).ready(function() {
        autosize($('textarea[class*=autosize]'));
    });

    function type_edit_show(){
        $('#modal-container').find('.modal-dialog').addClass('modal-sm');
        $("#modal-header-container").empty();
        $("#modal-body-container").empty();
        $('#modal-header-container').append('Редактирование');

        $.ajax({
            type: 'POST',
            url: "/dict/employee-needs-edit/",
            data: {},
            success: function(data){
                $("#modal-body-container").html(data);
            }
        });
        $("#modal-container").filter('.modal').modal();

    }

    function saveStatus(employee_needs_id, ob){
        $.ajax({
            type: 'POST',
            url: "/dict/employee-needs/mode/upd-status/",
            data: {employee_needs_id : employee_needs_id, status_id : ob.value},
            success: function(data){
                console.log(data);
                if(data.result['status'] == false){
                    alert(data.result['error']);
                    Notify.generate('Ошибка при изменении', '', 3);
                } else{
                    Notify.generate('Успешно', '', 1);
                }
            }
        });
    }
</script>