<style>
    table {
        border-collapse: collapse;
    }

    table, td, th {
        border: 1px solid black;
    }
</style>
<div class="table-responsive">
    <table class="table table-striped table-bordered table-responsive no-margin no-padding" id="table_1">
        <input type="hidden" name="reload_type" id="reload_type">
        <thead>
        <tr>
            <?
            if(count($this->row) > 0){?>
                <th>№</th>
                <?foreach ($this->row[0] as $key => $value){
                    ?>
                    <th><?=$key?></th>
                    <?
                }
            }
            ?>

        </tr>
        </thead>
        <tbody>
        <?
        $i = 1;
        $cur_date = date('d.m.Y');
        $cur_date = strtotime($cur_date);
        $dwg_date = '';
        $okk_date = '';
        $mp_date = '';
        $tmp = '';
        if(count($this->row) > 0){
            foreach ($this->row as $key => $value){
                ?>
                <tr>
                    <td><span style="float: right"><?=$i?></span></td>
                    <?
                    foreach ($value as $key1 => $value1){
                        ?>
                        <td><?=$value1?></td>
                        <?
                    }?>
                </tr>
                <?
                $i++;
            }
        }
        ?>
        </tbody>
    </table>
</div>