<div class="modal-body">
    <?
    if (isset($this->row['error'])) {?>
        <div class="alert alert-danger">
            <?=$this->row['error']?>
        </div>
        <?
    }?>
    <div class="clearfix"></div>
    <div class="">
        <form id="form_type">
            <input type="hidden" value="<?=$this->material_id?>" name="material_id">
            <div class="col-lg-12">
                <div class="form-group">
                    <label class="control-label " for="material_name">Кол-во</label>
                    <input type="number" step="any" id="cnt" placeholder="кол-во" class="form-control" value="<?=$this->row['cnt']?>" name="cnt">
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
            <div class="col-lg-12">
                <div class="form-group">
                    <label class="control-label " for="type">Тип</label>
                    <select class="form-control" id="type" name="type" required>
                        <option value="1">Приход</option>
                        <option value="2">Расход</option>
                    </select>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </form>
    </div>
</div>
<div class="modal-footer no-margin-top">
    <button type="button" class="btn btn-sm btn-success" id="btn_photo" onclick="saveMaterialMove()">
        <i class="ace-icon fa fa-check"></i>
        Сохранить
    </button>
    <button class="btn btn-sm btn-danger" data-dismiss="modal">
        <i class="ace-icon fa fa-times"></i>
        Закрыть
    </button>
</div>
<script>
    function saveMaterialMove(){
        var send_data = $('#form_type').serializeArray();
        $.ajax({
            type: 'POST',
            url: "/dict/material-move-list/mode/upd/",
            data:  send_data,
            success: function(data){
                if(data.result['status']){
                    $('.modal').modal('hide');
                    location.reload();
                }else{
                    alert(data.result['error'])
                }
            }
        });
    }
</script>

