<div class="page-header">
    <h1 class="pull-left">Движение по материалов по: <?=$this->row_material['material_name']?></h1>
    <div class="clearfix"></div>
</div>
<div class="hr hr-10 dotted hr-double"></div>
<a href="javascript:void(0)" onclick="move_edit(<?=$this->material_id?>)" class="btn btn-info btn-xs pull-right">Добавить</a>
<div class="clearfix"></div>
<div class="row-fluid">
    <div class="tabbable">
        <table id="main_table" class="table-local table-striped table-bordered hover-table no-margin-bottom no-border-top">
            <thead>
            <tr>
                <th>Кол-во</th>
                <th>Тип</th>
                <th>Работник</th>
                <th>Время</th>
            </tr>
            </thead>
            <tbody>
            <?
            if(mycount($this->row) > 0){
                foreach ($this->row as $key => $value){?>
                    <tr>
                        <td class="text-right"><?=$value['cnt']?></td>
                        <td class="text-left"><?=$value['type_text']?></td>
                        <td class="text-left"><?=$value['fio']?></td>
                        <td class="text-left"><?=$value['move_date']?></td>
                    </tr>
                    <?
                }
            }
            ?>
            </tbody>
        </table>
    </div>
</div>
<?=$this->partial('dict/modal-container.phtml');?>

<script>
    $(document).ready(function() {
        autosize($('textarea[class*=autosize]'));
    });

    function move_edit(material_id){
        $('#modal-container').find('.modal-dialog').addClass('modal-sm');
        $("#modal-header-container").empty();
        $("#modal-body-container").empty();
        $('#modal-header-container').append('Редактирование');

        $.ajax({
            type: 'POST',
            url: "/dict/material-move-edit/",
            data: {"material_id" : material_id},
            success: function(data){
                $("#modal-body-container").html(data);
            }
        });
        $("#modal-container").filter('.modal').modal();

    }
</script>