<div id="modal-container" class="modal fade" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header no-padding">
                <div class="table-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        <span class="white">&times;</span>
                    </button>
                    <span id="modal-header-container"></span>
                </div>
            </div>
            <div id="modal-body-container"></div>
        </div>
    </div>
</div>
