<div class="page-header" style="display: flex; align-items: center; justify-content: space-between;">
    <h1>Отчёт по оплате мастерам  (<?=mycount($this->row)?>)</h1>

</div>
<div class="clearfix"></div>
<form method="get">
    <div class="form-group pull-left margin-right-10">
        <label class="control-label " for="okk_employee_id">работник</label>
        <div class="form-control no-padding">
            <select class="chosen-select form-control" id="employee_id" data-placeholder="Выберите работника..." name="employee_id">
                <option value="0"> </option>
                <?
                if(mycount($this->row_employee) > 0){
                    foreach ($this->row_employee as $key => $value){?>
                        <option value="<?=$value['employee_id']?>"  <?=is_selected_html($value['employee_id'], $this->employee_id)?>><?=$value['fio']?></option>
                        <?
                    }
                }?>
            </select>
        </div>
        <div class="clearfix"></div>
    </div>
    <button type="submit" name="search" class="btn btn-primary btn-xs small-caps btn-height pull-left for-with-label margin-right-10">
        <i class="ace-icon fa fa-search align-top bigger-125"></i>
        Поиск
    </button>
    <div class="clearfix"></div>
</form>
<div class="hr hr-10 dotted hr-double"></div>
<div class="table-responsive">
    <table class="table table-striped table-bordered hover-table no-margin-bottom no-border-top">
        <thead>
        <tr>
            <th>ID работы</th>
            <th>Работа</th>
            <th>Клиент</th>
            <th>Адрес</th>
            <th>Объем работы</th>
            <th>Цена за кв.м.</th>
            <th>Сумма</th>
        </tr>
        </thead>
        <tbody>
        <?
        $sum = 0;
        if(mycount($this->row) > 0){
            foreach ($this->row as $key => $value){
                ?>
                <tr>
                    <td class="text-right"><a href="/dict/work-detail/work_id/<?=$value['work_id']?>" target="_blank"><?=$value['work_id']?></a></td>
                    <td class="text-left"><?=$value['work_name']?></td>
                    <td class="text-left"><?=$value['client_fio']?></td>
                    <td class="text-left"><?=$value['address']?></td>
                    <td class="text-right"><?=tenge_text($value['mdf_total'])?></td>
                    <td class="text-right"><?=tenge_text($value['price'])?></td>
                    <td class="text-right"><?=tenge_text($value['total_price'])?></td>
                </tr>
                <?
                $sum = $sum + $value['total_price'];
            }
        }
        ?>
        <tr>
            <td colspan="6" class="text-left">Общая сумма:</td>
            <td class="text-right"><?=tenge_text($sum)?></td>
        </tr>
        </tbody>
    </table>
</div>
<script src="/js/filtable.min.js"></script>
<script>
    $(document).ready(function() {
        $(".chosen-select").chosen({
            allow_single_deselect: true,
            no_results_text: "Ничего не найдено..."
        });
        $('.table').filtable({
            controlPanel: $('.table-filters')
        });
    });
</script>