<div class="page-header">
    <h1 class="pull-left">
        Заявки
        <?
        if($this->status_id == 1){
            echo '(Создан)';
        }elseif ($this->status_id == 2){
            echo '(Оплачено)';
        }elseif ($this->status_id == 3){
            echo '(В работе)';
        }elseif ($this->status_id == 4){
            echo '(Завершен)';
        }else{
            echo '(Отменен)';
        }
        ?>
        (<?=mycount($this->row)?>)
    </h1>
    <div class="btns-block pull-right">
        <a href="/dict/create-request/" class="btn btn-xs btn-primary">Создать</a>
    </div>
    <div class="clearfix"></div>
</div>

<div class="hr hr-10 dotted hr-double"></div>
<div class="table-responsive" id="account_load">
    <table class="table-local table-striped table-bordered hover-table no-margin-bottom no-border-top" id="account_tab">
        <thead>
        <tr>
            <th style="width: 10px;">ID</th>
            <th>Клиент ФИО</th>
            <th>Адрес</th>
            <th>Телефон</th>
            <th>Площадь</th>
            <th>Время замера</th>
            <th>Дата создания</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?
        foreach ( (array) $this->row as $key => $value){?>
            <tr>
                <td class="text-right"><?=$value['request_id']?></td>
                <td class="text-left">
                    <a href="/dict/request-edit/request_id/<?=$value['request_id']?>/"><?=$value['client_fio']?></a>
                </td>
                <td class="text-left"><?=$value['address']?></td>
                <td class="text-left"><?=$value['client_phone']?></td>
                <td class="text-right"><?=$value['house_area']?></td>
                <td class="text-right"><?=$value['measure_time']?></td>
                <td class="text-right"><?=$value['rowversion']?></td>
                <td class="text-center">
                    <?if(in_array(getCurPositionCode(), array('ADMIN'))){?>
                        <a class="btn btn-sm btn-primary" style="width: 90px;" href="javascript:void(0);" <?if($value['request_status_id'] == 3){?>disabled="true" <?}?> onclick="upd_status(<?=$value['request_id']?>, 3, this)">
                            В работе
                        </a>
                        <br>
                        <a class="btn btn-sm btn-success" style="width: 90px; margin-top: 5px;" href="javascript:void(0);" <?if($value['request_status_id'] == 4){?>disabled="true" <?}?> onclick="upd_status(<?=$value['request_id']?>, 4, this)">
                            Завершен
                        </a>
                        <br>
                        <a class="btn btn-sm btn-danger" style="width: 90px; margin-top: 5px;" href="javascript:void(0);" <?if($value['request_status_id'] == 5){?>disabled="true" <?}?> onclick="upd_status(<?=$value['request_id']?>, 5, this)">
                            Отменен
                        </a>
                    <?}?>
                </td>
            </tr>
            <?
        }
        ?>
        </tbody>
    </table>
</div>
<?=$this->partial('dict/modal-container.phtml');?>

<script>
    function showEditForm(request_id){
        $('#modal-container').find('.modal-dialog').addClass('modal-sm');
        $("#modal-header-container").empty();
        $("#modal-body-container").empty();
        $('#modal-header-container').append('Добавление/Редактирование счёта');
        $.ajax({
            type: 'POST',
            url: "/dict/account-edit/",
            data: {
                request_id : request_id
            },
            async: true,
            success: function(data){
                $("#modal-body-container").html(data);
            }
        });
        $("#modal-container").filter('.modal').modal();
    }

    function upd_status(request_id, status_id, ob){
        if (!confirm('Вы действительно хотите поменять статус?')) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/dict/request-list/mode/upd-status/request_id/" + request_id + "/status_id/" + status_id + "/",
            success: function(data){
                if(data.result['status'] == false){
                    Notify.generate('Ошибка', '', 3);
                    alert(data.result['error']);
                }
                else{
                    Notify.generate('Статус отменен', '', 1);
                    location.reload();
                }
            }
        });
    }


</script>
