<div class="modal-body">
    <?
    if (isset($this->row['error'])) {?>
        <div class="alert alert-danger">
            <?=$this->row['error']?>
        </div>
        <?
    }?>
    <div class="clearfix"></div>
    <div class="">
        <form id="form_type">
            <input type="hidden" value="<?=$this->employee_id?>" name="employee_id">
            <div class="col-lg-12">
                <div class="form-group">
                    <label class="control-label " for="material_name">Цена</label>
                    <input type="text" id="price" placeholder="Цена" class="form-control" name="price">
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
            <div class="col-lg-12">
                <label class="control-label no-padding-right" for="date_begin">Дата начала</label>
                <input type="text" style="width: 166px; height: 34px" id="date_begin" name="date_begin" placeholder="Дата начала" class="form-control date-picker" autocomplete="off">
            </div>
            <div class="col-lg-12">
                <label class="control-label no-padding-right" for="date_end">Дата конец</label>
                <input type="text" style="width: 166px; height: 34px" id="date_end" name="date_end" placeholder="Дата конец" class="form-control date-picker" autocomplete="off">
            </div>
            <div class="clearfix"></div>
        </form>
    </div>
</div>
<div class="modal-footer no-margin-top">
    <button type="button" class="btn btn-sm btn-success" id="btn_photo" onclick="workEmployeeSave()">
        <i class="ace-icon fa fa-check"></i>
        Сохранить
    </button>
    <button class="btn btn-sm btn-danger" data-dismiss="modal">
        <i class="ace-icon fa fa-times"></i>
        Закрыть
    </button>
</div>
<script>
    $(document).ready(function() {
        $(".date-picker").datepicker({
            changeMonth: true,
            changeYear: true,
            yearRange: "-100:+5"
        });
    });
    function workEmployeeSave(){
        var send_data = $('#form_type').serializeArray();
        $.ajax({
            type: 'POST',
            url: "/dict/work-employee-list/mode/upd/",
            data:  send_data,
            success: function(data){
                if(data.result['status']){
                    $('.modal').modal('hide');
                    location.reload();
                }else{
                    alert(data.result['error'])
                }
            }
        });
    }
</script>

