<table class="table table-striped table-bordered hover-table no-margin-bottom no-border-top">
    <thead>
    <tr>
        <th>ID</th>
        <th>Дата</th>
        <th>Пользователь</th>
        <th>Должность</th>
        <th>Комментарий</th>
        <th>Вложения</th>
    </tr>
    </thead>
    <tbody>
    <?
    $i = 1;
    $ob = new Application_Model_DbTable_Dict();
    foreach ($this->row as $key1 => $value){
        $doc_row = $ob->read_comment_file($value['work_comment_id'])['value'];
        ?>
        <tr>
            <td class="text-right"><?=$i?></td>
            <td class="text-center"><?=$value['comment_date']?></td>
            <td class="text-left"><?=$value['fio']?></td>
            <td class="text-left"><?=$value['position_name']?></td>
            <td class="text-left"><?=$value['comment']?></td>
            <td class="text-center">
                <?foreach ($doc_row as $key2 => $docs){
                    $file_ext = explode(".", $docs['document_name']);
                    if($file_ext[1] == 'pdf' or $file_ext[1] == 'doc' or $file_ext[1] == 'docx' or $file_ext[1] == 'txt'){
                        ?>
                        <a href="<?=$docs['document_url']?>" target="_blank" style="margin-right: 5px;" download><?=$docs['document_name']?></a>
                        <br>
                        <?
                    }else{
                        ?>
                        <a href="<?=$docs['document_url']?>" target="_blank" class="group1" style="margin-right: 5px;" download><?=$docs['document_name']?></a>
                        <br>
                        <?
                    }
                }?>
            </td>
        </tr>
        <?
        $i++;
    }?>
    </tbody>
</table>
<script>
    $( document ).ready(function() {
        $(".group1").colorbox({
            rel:'group1',
            photo:true,
            previous:'<i class="ace-icon fa fa-arrow-left"></i>',
            next:'<i class="ace-icon fa fa-arrow-right"></i>',
            close:'&times;',
            scalePhotos: true,
            scrolling:false,
            maxWidth: '100%',
            maxHeight:'100%',
            width: '50%',
            weight:'50%',
            reposition:true,
            onOpen:function(){
                $overflow = document.body.style.overflow;
                document.body.style.overflow = 'hidden';
            },
            onClosed:function(){
                document.body.style.overflow = $overflow;
            },
            onComplete:function(){
                $.colorbox.resize();
            }
        });

    });
</script>