<div class="col-lg-4">
    <div class="widget-box">
        <div class="widget-header">
            <h4 class="widget-title">Статусы работ</h4>
        </div>
        <div class="widget-body">
            <div class="widget-main">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered hover-table no-margin-bottom no-border-top">
                        <thead>
                        <tr>
                            <th></th>
                            <th></th>
                            <th>Статус</th>
                            <th>Дата</th>
                            <th>ФИО</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?
                        if(mycount($this->row_mark) > 0){
                            foreach ($this->row_mark as $key => $value){?>
                                <tr>
                                    <td class="text-center">
                                        <span class="blue bigger-140" data-toggle="popover" data-trigger="hover" data-placement="right" data-content="<?=$value['comment']?>">
                                            <i class="fa fa-question-circle" aria-hidden="true"></i>
                                        </span>
                                    </td>
                                    <td class="text-center">
                                        <input type="checkbox" <?if($value['is_checked'] > 0 && getCurPositionCode() != 'ADMIN'){echo 'disabled';}?> <?if($value['is_checked'] > 0 ){echo 'checked';}?> name="mark_checkbox" onclick="status_check('<?=$value['code']?>', this)">
                                    </td>
                                    <td class="text-left"><?=$value['name']?></td>
                                    <td class="text-left"><?=$value['date_mark']?></td>
                                    <td class="text-left"><?=$value['fio']?></td>
                                </tr>
                                <?
                            }
                        }
                        ?>
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
<script>
    $(document).ready(function(){
        $('[data-toggle="popover"]').popover();
    });
    function status_check(mark_type_code, ob) {
        if (!confirm('Вы действительно хотите изменить статус этапа?')) {
            $(ob).prop('checked', false);
            return false;
        }
        $.ajax({
            url: "/dict/index-json/mode/work-mark-check/work_id/<?=$this->work_id?>/mark_type_code/" + mark_type_code + "/",
            type: 'POST',
            success:function(data){
                if(data.result['status']){
                    window.location.href = window.location.href;
                }else{
                    if ($(ob).is(':checked')) {
                        $(ob).prop('checked', false);
                    } else {
                        $(ob).prop('checked', true);
                    }
                    alert(data.result['error']);
                }
            }
        });
    }
</script>