<?
if (isset($this->row['error'])) {?>
    <div class="alert alert-danger">
        <?=$this->row['error']?>
    </div>
    <?
}?>
<div class="modal-body">
    <form id="measure_item">
        <input type="hidden" name="measure_type_id" value="<?=$this->measure_type_id?>">
        <input type="hidden" name="work_id" value="<?=$this->work_id?>">
        <div class="form-group">
            <label class="control-label" for="name">Высота</label>
            <input type="number" step="any" class="form-control" name="height" id="height" required>
            <div class="clearfix"></div>
        </div>
        <div class="form-group">
            <label class="control-label" for="name">Ширина</label>
            <input type="number" step="any" class="form-control" name="length" id="length" required>
            <div class="clearfix"></div>
        </div>
        <div class="form-group">
            <label class="control-label" for="name">Кол-во</label>
            <input type="number" step="any" class="form-control" name="cnt" value="<?=$this->row['cnt']?>" id="cnt" required>
            <div class="clearfix"></div>
        </div>
    </form>
</div>
<div class="modal-footer no-margin-top">
    <button type="button" class="btn btn-sm btn-success" onclick="work_measure_upd(<?=$this->measure_type_id?>)">
        <i class="ace-icon fa fa-check"></i>
        Сохранить
    </button>
    <button class="btn btn-sm btn-danger" data-dismiss="modal">
        <i class="ace-icon fa fa-times"></i>
        Закрыть
    </button>
</div>

<script>
    $(document).ready(function() {
        $(".date-picker").datepicker({
            changeMonth: true,
            changeYear: true,
            yearRange: "-100:+5"
        });
    });
</script>